name: tgsheduler
services:
  bot:
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: go_bot
    restart: unless-stopped
    volumes:
      - ../configs/.env:/app/.env
    networks:
      - dev-network
    depends_on:
      - postgres
      - redis
    ports:
      - "9091:9091"

  postgres:
    image: postgres:18.1-alpine3.23
    volumes:
      - pdata:/var/lib/postgresql/data
      # - ./postgres:/docker-entrypoint-initdb.d
    restart: always
    container_name: pg_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - dev-network

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev-network
    command: redis-server --save 60 1 --loglevel warning

  asynqmon:
    image: hibiken/asynqmon
    container_name: asynqmon
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - dev-network
    command: --redis-addr=redis:${REDIS_PORT}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    networks:
      - dev-network

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - dev-network

networks:
  dev-network:


volumes:
  pdata:
  grafana-data:
